### ISSUE TITLE
GTFS parsing error : missing trip_headsign

### ISSUE THREAD

**Issue by gtracy** [gtracy/madison-transit-api-gtfs#11]
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Cannot read property 'trip_headsign' of undefined",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Cannot read property 'trip_headsign' of undefined",
        "stack": [
            "TypeError: Cannot read property 'trip_headsign' of undefined",
            "    at /var/task/api/schedule.js:49:43",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'trip_headsign' of undefined",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:400:28)",
        "    at process.emit (domain.js:475:12)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
    ]
}

**Comment by gtracy** [comment]
The root cause is that the real-time feed is returning results with trip IDs that cannot be found in the trips.txt GTFS file. Here are some examples I've found so far. 

- 1079107
- 1079075
- 1079106
- 1079076

**Comment by gtracy** [comment]
Theory from the Metro is that these are special buses for schools and other things which aren't part of the system but still report on the RT feed.
