### ISSUE TITLE
TypeError: Cannot read property 'route_short_name' of undefined

### ISSUE THREAD

**Issue by gtracy** [gtracy/madison-transit-api-gtfs#14]
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Cannot read property 'route_short_name' of undefined",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Cannot read property 'route_short_name' of undefined",
        "stack": [
            "TypeError: Cannot read property 'route_short_name' of undefined",
            "    at /var/task/api/schedule.js:70:77",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'route_short_name' of undefined",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:400:28)",
        "    at process.emit (domain.js:475:12)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
    ]
}

**Comment by gtracy** [comment]
Example of a trip with a bad GTFS route ID,

    "feed_time": {
        "low": 1643401939,
        "high": 0,
        "unsigned": true
    },
    "stop": {
        "stopSequence": 9,
        "departure": {
            "time": "1643407158"
        },
        "stopId": "5683"
    },
    "routeId": "9962",
    "tripId": "1079070",
    "vehicle": {
        "id": "2322",
        "label": "910"
    },

**Comment by gtracy** [comment]
another example,

    "feed_time": {
        "low": 1643403590,
        "high": 0,
        "unsigned": true
    },
    "stop": {
        "stopSequence": 1,
        "departure": {
            "time": "1643406420"
        },
        "stopId": "1141"
    },
    "routeId": "9977",
    "tripId": "1079241",
    "vehicle": {
        "id": "2314",
        "label": "903"
    }

**Comment by gtracy** [comment]
current app solution is to mark the route ID as 'unknown' in the results payload to the client. 

Metro claims that these are special buses for schools and other functions that don't fall inside the core system. 

i'm going to leave the ticket open for now and see if Metro changes the GTFS data based on my feedback.

**Comment by gtracy** [comment]
closing since this is a data issue in Metro's GTFS data. i've mitigated the blast radius in the code
