### ISSUE TITLE
missing data fields in fetch_trips throws TypeError

### ISSUE THREAD

**Issue by gtracy** [gtracy/madison-transit-api-gtfs#16]
{
    "level": 50,
    "time": 1643398528520,
    "pid": 14,
    "hostname": "169.254.50.249",
    "err": {
        "type": "TypeError",
        "message": "Cannot read property 'id' of null",
        "stack": "TypeError: Cannot read property 'id' of null\n    at /var/task/api/fetch.js:53:73\n    at Array.forEach (<anonymous>)\n    at /var/task/api/fetch.js:45:54\n    at Array.forEach (<anonymous>)\n    at Object.module.exports.fetch_trips (/var/task/api/fetch.js:42:21)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /var/task/api/schedule.js:30:23"
    },
    "msg": "Cannot read property 'id' of null"
}

**Comment by gtracy** [comment]
d57b3f4a796d24c6f161aea38d808b745e0dd253

**Comment by gtracy** [comment]
closing since this is a data issue in Metro's GTFS data. i've mitigated the blast radius in the code
