### ISSUE TITLE
Runtime error on missing dev key

### ISSUE THREAD

**Issue by gtracy** [gtracy/madison-transit-api-gtfs#23]
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Cannot read property 'toLowerCase' of undefined",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Cannot read property 'toLowerCase' of undefined",
        "stack": [
            "TypeError: Cannot read property 'toLowerCase' of undefined",
            "    at module.exports.validateDevKey (/var/task/api/devkey.js:21:39)",
            "    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)",
            "    at next (/var/task/node_modules/express/lib/router/route.js:137:13)",
            "    at module.exports.afterHours (/var/task/api/utils.js:21:9)",
            "    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)",
            "    at next (/var/task/node_modules/express/lib/router/route.js:137:13)",
            "    at Route.dispatch (/var/task/node_modules/express/lib/router/route.js:112:3)",
            "    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)",
            "    at /var/task/node_modules/express/lib/router/index.js:281:22",
            "    at Function.process_params (/var/task/node_modules/express/lib/router/index.js:341:12)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'toLowerCase' of undefined",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:400:28)",
        "    at process.emit (domain.js:475:12)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
    ]
}

**Comment by gtracy** [comment]
resolved with db78ee461e1665202804d864c0df8fecfa882733
