### ISSUE TITLE
missing vehicle details in RT feed

### ISSUE THREAD

**Issue by gtracy** [gtracy/madison-transit-api-gtfs#24]
{
    "level": 50,
    "time": 1645024238157,
    "pid": 22,
    "hostname": "169.254.194.57",
    "err": {
        "type": "TypeError",
        "message": "Cannot read property 'id' of null",
        "stack": "TypeError: Cannot read property 'id' of null\n    at Object.module.exports.getValue (/var/task/api/utils.js:67:19)\n    at /var/task/api/fetch.js:54:53\n    at Array.forEach (<anonymous>)\n    at /var/task/api/fetch.js:46:54\n    at Array.forEach (<anonymous>)\n    at Object.module.exports.fetch_trips (/var/task/api/fetch.js:43:21)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /var/task/api/schedule.js:33:23"
    },
    "msg": "Cannot read property 'id' of null"
}

**Comment by gtracy** [comment]
The most common culprit that led to the error was when Metro loses access to the vehicle details on the RT feed for whatever reason. 

The vehicle data is not critical to the /schedule API, and it is not uncommon for the vehicle details to disappear from the Metro feed from time to time based on what I'm seeing in my own logs. Rather than logging internal errors for missing data, test for the missing vehicle data and adjust my payload accordingly.
```

                            trips.push({
                                'feed_time' : feed.header.timestamp,
                                'stop'    : stop,
                                'routeId' : entity.tripUpdate.trip.routeId,
                                'tripId'  : entity.tripUpdate.trip.tripId,
                                'vehicle' : {
                                    'id'    : utils.getValue(entity.tripUpdate.vehicle,"id",true),
                                    'label' : utils.getValue(entity.tripUpdate.vehicle,"label",true)
                                }
                            });

```
