### ISSUE TITLE
Error thrown when a routeID filter is applied to getarrivals and the route is not live

### ISSUE THREAD

**Issue by gtracy** [gtracy/madison-transit-api-gtfs#38]
The end user experience appears graceful but this error is being thrown on the requests.

{
    "level": 50,
    "time": 1662035462719,
    "pid": 15,
    "hostname": "169.254.5.97",
    "err": {
        "type": "TypeError",
        "message": "Cannot read property 'route_id' of undefined",
        "stack": "TypeError: Cannot read property 'route_id' of undefined\n    at /var/task/api/fetch.js:44:40\n    at Array.forEach (<anonymous>)\n    at Object.module.exports.fetch_trips (/var/task/api/fetch.js:42:21)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /var/task/api/schedule.js:33:23"
    },
    "msg": "Cannot read property 'route_id' of undefined"
}

**Comment by gtracy** [comment]
the fix is not complete. re-opening.
